#数据库连接
spring:
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        content-type: text/html
        mode: LEGACYHTML5
    datasource:
        url: jdbc:mysql://localhost:3306/park?characterEncoding=utf8&useSSL=true
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
#服务器端口
server:
  port: 8088
#  session:
#    timeout: 1

